<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Admin Home Page</title>
</head>
<body bgcolor="gray">
   <div style="width:1500px; background:yellow">
   <h4 align="center">Given origin and destination, all past flights,states,passenger counts data</h4>
   <form action="scheduleHistory" method="post" align="center">
   Origin<input type="text" name="from_port" required><br/></br>
   Destination<input type="text" name="to_port" required></br></br>
   <input type="submit" value="check">
   </form>
   </div>
   
   <div style="width:1500px; background:pink">
   <h4 align="center">Given a flight no, all passengers traveling in it(next immediate flight) below age 18, above age 18</h4>
   <form action="flight_passenger_info" method="post" align="center">
   Flight Id<input type="text" name="flight_id"><br/></br>
   <input type="submit" value="check">
   </form>
   </div>
   
   
   <div style="width:1500px; background:orange">
   <h4 align="center">Given a date range, number of passengers traveling to a given destination</h4>
   <form action="destination_passenger_info" method="post" align="center">
   From date<input type="date" name="from_date" required><br/></br>
   To date<input type="date" name="to_date" required><br/></br>
   Destination<input type="text" name="destination" required><br/></br>
   <input type="submit" value="check">
   </form>
   </div>
   
   <div style="width:1500px; background:purple">
   <h4 align="center">Given a date range, number of bookings by each passenger type</h4>
   <form action="passenger_type_count" method="post" align="center">
   From date<input type="date" name="from_date_2" required><br/></br>
   To date<input type="date" name="to_date_2" required><br/></br>
   <input type="submit" value="check">
   </form>
   </div>
   
   <div style="width:1500px; background:blue">
   <h4 align="center">Total revenue generated by each aircraft type</h4>  
   <form action="total_revenue_aircraft" method="post" align="center">
   <input type="submit" value="check">
   </div>
</body>
</html>